keycloak:
  realm: Biobank
  auth-server-url: http://${KEYCLOAK_HOST}:8180/auth
  resource: biobank
  bearer-only: true
  ssl-required: none 
  principal-attribute: subject
  use-resource-role-mappings: true

  securityConstraints:
    - authRoles: [role-biobank]
      securityCollections:
        - name: Biobank private API's
          patterns: ['/biobank/*']

spring:
  jpa:
    hibernate:
      generate-ddl: false
  datasource:
      url: jdbc:mysql://${MYSQL_HOST}:3306/biobank_db?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: admin
      password: admin
      initialization-mode: always

server:
  port: 9093